"""fix migration

Revision ID: 06e05e43bbe8
Revises: cc115a2c8db4
Create Date: 2025-03-27 02:48:45.752641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e05e43bbe8'
down_revision: Union[str, None] = 'cc115a2c8db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_sessions', sa.Column('proxy_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'telegram_sessions', 'proxy_settings', ['proxy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_sessions', type_='foreignkey')
    op.drop_column('telegram_sessions', 'proxy_id')
    # ### end Alembic commands ###
