"""Add is_active column to telegram_sessions

Revision ID: 9fba597aaeb6
Revises: a672cd0364b3
Create Date: 2025-03-30 01:21:47.007704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fba597aaeb6'
down_revision: Union[str, None] = 'a672cd0364b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_sessions', 'is_active')
    # ### end Alembic commands ###
